//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amistades
    {
        public int AmistadId { get; set; }
        public int UsuarioSolicitanteId { get; set; }
        public int UsuarioAceptadoId { get; set; }
        public int EstadoAmistad { get; set; }
    
        public virtual EstadoAmistad EstadoAmistad1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
