//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int ComentarioId { get; set; }
        public string Contenido { get; set; }
        public System.DateTime FechaHoraComentario { get; set; }
        public int UsuarioId { get; set; }
        public int PublicacionId { get; set; }
        public int EstadoComentario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Publicaciones Publicaciones { get; set; }
    }
}
